### ISSUE TITLE
No ant logging in case ant runs in an environment with other logging framework available on classpath

### ISSUE THREAD

**Issue by gahoekstraibm** [flyway/flyway-ant#8]
Hi,

We are using flyway-ant in our project and are busy upgrading Flyway and flyway-ant to a recent version. Doing so, we noticed that Flyway logging disappeared, most probably because flyway-ant now sets a fallback logger, which will not be used in case the environment is also having a different logger available on the classpath that is supported by Flyway (which seems to be the case for us).  

What would be the proper way to force Flyway to use the fallback logger set by flyway-ant? setting the flyway.logger configuration property to include console perhaps?

Regards,

Geert Hoekstra

**Comment by ttulka** [comment]
Hi, thanks for raising up the issue!

In the new release `2.18.0` I have added a new property `flyway.loggers` to control the used logger. You can set it to `console` to use the fallback logger (Ant logger).

**Comment by gahoekstraibm** [comment]
Hi, With the latest changes, running multiple subsequent Flyway tasks fails with "Flyway Error: null source". Probably some statements need to stay in the init method?

Moving the setting of the fallback logger and creation of the logger back to init resolved the issue (where LogFactory.getLog(...) is invoked after calling Flyway.configure(..) method)

**Comment by ttulka** [comment]
Could you provide a minimal example to reproduce this behavior?

**Comment by gahoekstraibm** [comment]
From within the same ant project, we use multiple flyway:migrate calls (to migrate multiple different schemas).

**Comment by ttulka** [comment]
I moved the fallback logger initialization into the init method. I tried to reproduce the problem according to your description, but all works as expected: https://github.com/ttulka/flyway-ant-test 

Could you provide more details or tell me what is the difference?

**Comment by gahoekstraibm** [comment]
Hi Tomas, the latest code works fine. 

It may be triggered in my specific situation as I have two database types registered that use the same JDBC URL, causing debug logging as part of the Flyway.configuration(...) invocation, which was being executed prior to initializing the ant fallback logger.
See below stack trace:

`Caused by: java.lang.IllegalArgumentException: null source
        at java.util.EventObject.<init>(EventObject.java:67)
        at org.apache.tools.ant.BuildEvent.<init>(BuildEvent.java:90)
        at org.apache.tools.ant.Project.fireMessageLogged(Project.java:2057)
        at org.apache.tools.ant.Project.log(Project.java:367)
        at org.flywaydb.ant.AntLog.debug(AntLog.java:31)
        at org.flywaydb.core.internal.logging.multi.MultiLogger.debug(MultiLogger.java:45)
        at org.flywaydb.core.internal.logging.EvolvingLog.debug(EvolvingLog.java:52)
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:50)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:89)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1557)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1282)
        at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:941)
        at org.flywaydb.ant.AbstractFlywayTask.execute(AbstractFlywayTask.java:629)
        ... 34 more
`
