### ISSUE TITLE
No database found to handle jdbc:...

### ISSUE THREAD

**Issue by tcrass** [flyway/flyway-ant#9]
Hi,

I'm trying to set up an ant build calling some of the flyway-ant targets, but I always end up with build failures saying

```
Flyway Error: No database found to handle jdbc:mariadb://<some_host>:3306/<some_db>
```

or similar (different JDBC urls, depending on configuration). In `build.xml`, I'm referencing a fat jar which definitely contains all classes from `flyway-core`, `flyway-mysql`, `flyway-ant` and various JDBC driver packages, including mariadb, mysql and others:

```
<path id="tools.lib.classpath" location="path/to/my/fat.jar" />

<path id="flyway.lib.path" refid="tools.lib.classpath" />
<path id="flyway.classpath" >
    <pathelement path="path/to/my/sql/migrations"/>
    <path refid="tools.lib.classpath"/>
</path>
<taskdef uri="antlib:org.flywaydb.ant" resource="org/flywaydb/ant/antlib.xml" classpathref="flyway.lib.path" />

<target name="db-info">
    <property name="flyway.url" value="jdbc:mariadb://<some_host>:3306/<some_db>" />
    <property name="flyway.user" value="some_user" />
    <property name="flyway.password" value="psst!" />
    <flyway:info/>
</target>
``` 

-----
EDIT 2023-05-04:

The stacktrace

```
No database found to handle jdbc:mariadb://<some_host>:3306/<some_db>
        at org.flywaydb.ant.AbstractFlywayTask.execute(AbstractFlywayTask.java:674)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:827)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mariadb://localhost:3306/bingo
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:55)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:89)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1653)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1357)
        at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:1026)
        at org.flywaydb.ant.AbstractFlywayTask.execute(AbstractFlywayTask.java:646)
        ... 16 more

```

suggests that the `REGISTERED_PLUGINS` array in `org.flywaydb.core.internal.plugin.PluginRegister` does not get filled properly by the call to `ServiceLoader.load(Plugin.class, CLASS_LOADER)`, with `CLASS_LOADER` being `new PluginRegister().getClass().getClassLoader()`...AH! GOT IT! In its `META-INF/services` folder, my fat jar contains only the `org.flywaydb.core.extensibility.Plugin` file from `flyway-core`, not the service description file from `lyway-mysql` -- which is no wonder, since both files have the same name, and there can only be one file of that name in the fat jar. :-/ So I guess I'll have to re-think the way of distributing my app/lib...

-----
Anyway, this issue still remains:

I wanted to debug this issue by setting up flyway.lib.path like described in the documentation (i.e. by referencing multiple jars):

```
   <path id="flyway.lib.path">
       <!-- include all jars from the Flyway AntLib distribution -->
   </path>
```

However, it is not clear where to get "all jars from the Flyway AntLib distribution" from, since the releases on github only contain source code archives, but no (collections of) jars.

So could you please make the documentation a little bit more explicit about what jars exactly need to be on the flyway.lib.path?

(Of course, any direct advice on the "No database found to handle ..." problem would also be greatly appreciated... ;)

Cheers --
Torsten

**Comment by ttulka** [comment]
Hey @tcrass ,
You can download the JAR from https://central.sonatype.com, resp. https://central.sonatype.com/artifact/com.ttulka.flyway/flyway-ant/2.19.3/versions (click on Browse to see the files)

I can extend the doc, but feel free to send me a PR

Thanks!

**Comment by tcrass** [comment]
Hi @ttulka,

sorry for the delay in replying, I've been terribly busy for the last two weeks...

Anyway,

> You can download the JAR from https://central.sonatype.com/, resp. https://central.sonatype.com/artifact/com.ttulka.flyway/flyway-ant/2.19.3/versions (click on Browse to see the files)

I had no problem getting the jar for `flyway-ant` itself (maven did that for me), but I wasn't sure exactly which jar**s** (plural!) to include here:

```
   <path id="flyway.lib.path">
       <!-- include all jars from the Flyway AntLib distribution -->
   </path>
```

So it would be great if you could update the documentation accordingly.

Cheers --
Torsten

**Comment by ttulka** [comment]
@tcrass Hi, I have uploaded the ZIP archive into the last release and add the note to the README

**Comment by tcrass** [comment]
Excellent, thank you! :)

I suggest to close this issue now.

**Comment by tcrass** [comment]
Just a (late) note on the fat jar issue: I tried out what @fungtional wrote in his comment on my StackOverflow post regarding this issue (https://stackoverflow.com/questions/76162754/flyway-ant-no-database-found-to-handle-jdbc), and by using an AppendingTransformer while building my fat jar with the maven-shade-plugin I was able to retain the contents of all database vendors' org.flywaydb.core.extensibility.Plugin service definition files.

Cheers -- tcrass
